function [connections] = list_NeighborCities(city)

% Input "city" is a 1x1 cell array describing the city of interest
% Output "connections" are all the n cities to which a pawn could walk in a
% single action. Output is a 1xn cell array.

connectivity_matrix = cellstr([...
    "San Francisco" "Tokyo" "Manila" "Los Angeles" "Chicago" "NULL" "NULL";...
    "Los Angeles" "Sydney" "San Francisco" "Chicago" "Mexico City" "NULL" "NULL";...
    "Chicago" "San Francisco" "Los Angeles" "Mexico City" "Montreal" "Atlanta" "NULL";...
    "Mexico City" "Los Angeles" "Chicago" "Lima" "Bogota" "Miami" "NULL";...
    "Lima" "Mexico City" "Bogota" "Santiago" "NULL" "NULL" "NULL";...
    "Santiago" "Lima" "NULL" "NULL" "NULL" "NULL" "NULL";...
    "Atlanta" "Chicago" "Washington DC" "Miami" "NULL" "NULL" "NULL";...
    "Miami" "Atlanta" "Mexico City" "Bogota" "Washington DC" "NULL" "NULL";...
    "Bogota" "Mexico City" "Lima" "Miami" "Buenos Aires" "Sao Paolo" "NULL";...
    "Buenos Aires" "Bogota" "Sao Paolo" "NULL" "NULL" "NULL" "NULL";...
    "Montreal" "Chicago" "Washington DC" "New York" "NULL" "NULL" "NULL";...
    "Washington DC" "Atlanta" "Montreal" "Miami" "New York" "NULL" "NULL";...
    "New York" "Montreal" "Washington DC" "London" "Madrid" "NULL" "NULL";...
    "Sao Paolo" "Bogota" "Buenos Aires" "Madrid" "Lagos" "NULL" "NULL";...
    "London" "New York" "Madrid" "Paris" "Essen" "NULL" "NULL";...
    "Madrid" "New York" "London" "Sao Paolo" "Paris" "Algiers" "NULL";...
    "Paris" "London" "Madrid" "Essen" "Milan" "Algiers" "NULL";...
    "Algiers" "Madrid" "Paris" "Istanbul" "Cairo" "NULL" "NULL";...
    "Lagos" "Sao Paolo" "Kinshasa" "Khartoum" "NULL" "NULL" "NULL";...
    "Essen" "London" "Paris" "Milan" "St Petersburg" "NULL" "NULL";...
    "Milan" "Essen" "Paris" "Istanbul" "NULL" "NULL" "NULL";...
    "St Petersburg" "Essen" "Istanbul" "Moscow" "NULL" "NULL" "NULL";...
    "Istanbul" "Milan" "St Petersburg" "Moscow" "Baghdad" "Cairo" "Algiers";...
    "Cairo" "Algiers" "Istanbul" "Baghdad" "Riyadh" "Khartoum" "NULL";...
    "Khartoum" "Cairo" "Lagos" "Kinshasa" "Johannesburg" "NULL" "NULL";...
    "Kinshasa" "Lagos" "Khartoum" "Johannesburg" "NULL" "NULL" "NULL";...
    "Johannesburg" "Kinshasa" "Khartoum" "NULL" "NULL" "NULL" "NULL";...
    "Moscow" "St Petersburg" "Istanbul" "Tehran" "NULL" "NULL" "NULL";...
    "Baghdad" "Istanbul" "Tehran" "Karachi" "Riyadh" "Cairo" "NULL";...
    "Riyadh" "Cairo" "Baghdad" "Karachi" "NULL" "NULL" "NULL";...
    "Tehran" "Moscow" "Delhi" "Karachi" "Baghdad" "NULL" "NULL";...
    "Karachi" "Riyadh" "Baghdad" "Tehran" "Delhi" "Mumbai" "NULL";...
    "Mumbai" "Karachi" "Delhi" "Chennai" "NULL" "NULL" "NULL";...
    "Delhi" "Tehran" "Karachi" "Mumbai" "Chennai" "Kolkata" "NULL";...
    "Chennai" "Mumbai" "Delhi" "Kolkata" "Bangkok" "Jakarta" "NULL";...
    "Kolkata" "Delhi" "Chennai" "Bangkok" "Hong Kong" "NULL" "NULL";...
    "Bangkok" "Kolkata" "Chennai" "Jakarta" "Hong Kong" "Ho Chi Minh City" "NULL";...
    "Jakarta" "Chennai" "Bangkok" "Ho Chi Minh City" "Sydney" "NULL" "NULL";...
    "Beijing" "Seoul" "Shanghai" "NULL" "NULL" "NULL" "NULL";...
    "Shanghai" "Beijing" "Seoul" "Tokyo" "Taipei" "Hong Kong" "NULL";...
    "Hong Kong" "Shanghai" "Taipei" "Kolkata" "Bangkok" "Manila" "Ho Chi Minh City";...
    "Ho Chi Minh City" "Bangkok" "Hong Kong" "Manila" "Jakarta" "NULL" "NULL";...
    "Seoul" "Beijing" "Tokyo" "Shanghai" "NULL" "NULL" "NULL";...
    "Tokyo" "Seoul" "Shanghai" "Osaka" "San Francisco" "NULL" "NULL";...
    "Osaka" "Tokyo" "Taipei" "NULL" "NULL" "NULL" "NULL";...
    "Taipei" "Shanghai" "Osaka" "Hong Kong" "Manila" "NULL" "NULL";...
    "Manila" "Hong Kong" "Taipei" "San Francisco" "Sydney" "NULL" "NULL";...
    "Sydney" "Jakarta" "Manila" "Los Angeles" "NULL" "NULL" "NULL"...    
    ]);

dims = size(connectivity_matrix);
i = 1;
while i <= dims(1)
    if strcmp(connectivity_matrix(i,1),string(city))==true
        count = 0;
        for j = 2:7
            if strcmp(connectivity_matrix(i,j),"NULL")==false
                count = count + 1;
                connections(count) = connectivity_matrix(i,j);
            end
        end
        i = 12345; %Break loop
    end
    i=i+1;
end

end

